version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3003:3003"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5012
  
  backend:
    build: ./server
    ports:
      - "5012:5012"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/output:/app/output
      - ./server/temp:/app/temp
